name: Build and Upload Artifacts
on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew jar

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: PerWorldPlugins
          path: build/libs/**.jar
